[package]
name = "taskmeister"
version = "0.1.0"
edition = "2024"

[dependencies]
rustyline = "17.0.2"
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

